# Generated by Django 4.1 on 2022-08-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authingid', models.CharField(max_length=100, unique=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, '不适用'), (2, '男'), (3, '女'), (4, '非二元')], default=1)),
                ('age', models.PositiveSmallIntegerField(default=1)),
                ('motto', models.CharField(max_length=200)),
                ('nickname', models.CharField(default='新用户', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.question')),
            ],
        ),
    ]
