# Generated by Django 4.1 on 2022-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_authingusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authingid', models.CharField(max_length=100, unique=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, '不适用'), (2, '男'), (3, '女'), (4, '非二元')], default=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('motto', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthingUsers',
        ),
    ]
