# Generated by Django 4.1 on 2022-08-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_user_delete_authingusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='新用户', max_length=16),
        ),
    ]
