# Generated by Django 4.1 on 2022-08-12 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 18, 23, 53, 70098)),
        ),
    ]
