# Generated by Django 4.1 on 2022-08-12 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_userpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
