# Generated by Django 4.1 on 2022-08-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_follow_remove_user_followers_user_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='follower+', to='first.user'),
        ),
    ]
