# Generated by Django 4.1 on 2022-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_alter_follow_follower'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='avatar_url',
        #     field=models.URLField(default='https://voicebar-1251996605.cos.ap-shanghai.myqcloud.com/avatar/default_avatar.png'),
        # ),
    ]
