# Generated by Django 4.1 on 2022-08-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_like_user_likes_userpost_visited_count_like_post_and_more'),
        ('first', '0014_user_avatar_url'),
    ]

    operations = [
    ]
