# Generated by Django 4.1 on 2022-08-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_merge_20220815_0933'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='UserImage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('image_url', models.URLField()),
        #     ],
        # ),
        # migrations.RemoveField(
        #     model_name='userpost',
        #     name='is_main_post',
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_admin',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_banned',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='userpost',
        #     name='title',
        #     field=models.CharField(default='标题', max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='userpost',
        #     name='post',
        #     field=models.CharField(max_length=512),
        # ),
        # migrations.AddConstraint(
        #     model_name='follow',
        #     constraint=models.UniqueConstraint(fields=('user', 'follower'), name='unique_follow'),
        # ),
        # migrations.AddConstraint(
        #     model_name='like',
        #     constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_like'),
        # ),
        # migrations.AddField(
        #     model_name='userimage',
        #     name='creator',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.user'),
        # ),
    ]
