# Generated by Django 4.1 on 2022-08-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_userimage_remove_userpost_is_main_post_user_is_admin_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='userimage',
        #     name='post',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.userpost'),
        # ),
    ]
