# Generated by Django 4.1 on 2022-08-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_userimage_post'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='avatar_url',
        #     field=models.URLField(default='https://voicebar-1251996605.cos.ap-shanghai.myqcloud.com/avatar/default_avatar.png'),
        # ),
        # migrations.AddField(
        #     model_name='userpost',
        #     name='ip_loc',
        #     field=models.CharField(default='未知', max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='userimage',
        #     name='post',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='first.userpost'),
        # ),
        # migrations.CreateModel(
        #     name='UserVoice',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('voice_url', models.URLField()),
        #         ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.user')),
        #         ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='first.userpost')),
        #     ],
        # ),
    ]
