# Generated by Django 4.1 on 2022-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_alter_uservoice_post_useraitest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraitest',
            name='image_url',
            field=models.URLField(default='https://voicebar-1251996605.cos.ap-shanghai.myqcloud.com/avatar/default_avatar.png'),
        ),
    ]
